#include <ATen/native/CPUFallback.h>

#include <cstdlib>
#include <fstream>
#include <sstream>
#include <string>
#include <sys/stat.h>
#include <sys/types.h>

#include <torch/extension.h>
#include <torch/library.h>


namespace {

std::string codegen_dir() {
  const char* env_dir = std::getenv("MINIPU_CODEGEN_DIR");
  return env_dir == nullptr || std::string(env_dir).empty() ? "generated" : env_dir;
}

void ensure_codegen_dir() {
  const std::string dir = codegen_dir();
  mkdir(dir.c_str(), 0755);
}

void write_file(const std::string& path, const std::string& text) {
  std::ofstream out(path);
  out << text;
}

std::string cuda_kernel_for(const std::string& op_name, const std::string& expression) {
  std::ostringstream out;
  out << "// Generated by the MiniPU PrivateUse1 demo backend.\n";
  out << "// This is inspectable codegen, not a production runtime.\n\n";
  out << "#include <stddef.h>\n\n";
  out << "extern \"C\" __global__ void minipu_" << op_name
      << "_f32(const float* a, const float* b, float* out, size_t n) {\n";
  out << "  size_t i = blockIdx.x * blockDim.x + threadIdx.x;\n";
  out << "  if (i < n) {\n";
  out << "    out[i] = " << expression << ";\n";
  out << "  }\n";
  out << "}\n";
  return out.str();
}

void emit_kernel_sources(const std::string& op_name, const std::string& expression) {
  ensure_codegen_dir();
  const std::string dir = codegen_dir();
  write_file(dir + "/" + op_name + ".cu", cuda_kernel_for(op_name, expression));
}

void emit_add_sources() {
  static bool emitted = false;
  if (!emitted) {
    emit_kernel_sources("add", "a[i] + b[i]");
    emitted = true;
  }
}

void emit_mul_sources() {
  static bool emitted = false;
  if (!emitted) {
    emit_kernel_sources("mul", "a[i] * b[i]");
    emitted = true;
  }
}

void emit_relu_sources() {
  static bool emitted = false;
  if (!emitted) {
    emit_kernel_sources("relu", "a[i] > 0.0f ? a[i] : 0.0f");
    emitted = true;
  }
}

void emit_demo_codegen() {
  emit_add_sources();
  emit_mul_sources();
  emit_relu_sources();
}

void minipu_cpu_fallback(const c10::OperatorHandle& op, torch::jit::Stack* stack) {
  at::native::cpu_fallback(op, stack);
}

void minipu_add(const c10::OperatorHandle& op, torch::jit::Stack* stack) {
  emit_add_sources();
  at::native::cpu_fallback(op, stack);
}

void minipu_mul(const c10::OperatorHandle& op, torch::jit::Stack* stack) {
  emit_mul_sources();
  at::native::cpu_fallback(op, stack);
}

void minipu_relu(const c10::OperatorHandle& op, torch::jit::Stack* stack) {
  emit_relu_sources();
  at::native::cpu_fallback(op, stack);
}

}  // namespace


TORCH_LIBRARY_IMPL(aten, PrivateUse1, m) {
  m.impl("add.Tensor", torch::CppFunction::makeFromBoxedFunction<&minipu_add>());
  m.impl("mul.Tensor", torch::CppFunction::makeFromBoxedFunction<&minipu_mul>());
  m.impl("relu", torch::CppFunction::makeFromBoxedFunction<&minipu_relu>());
}


TORCH_LIBRARY_IMPL(_, PrivateUse1, m) {
  m.fallback(torch::CppFunction::makeFromBoxedFunction<&minipu_cpu_fallback>());
}


TORCH_LIBRARY_IMPL(_, AutocastPrivateUse1, m) {
  m.fallback(torch::CppFunction::makeFallthrough());
}


PYBIND11_MODULE(TORCH_EXTENSION_NAME, m) {
  m.def("is_registered", []() { return true; });
  m.def("codegen_dir", &codegen_dir);
  m.def("emit_demo_codegen", &emit_demo_codegen);
}
